filter:
  excluded_paths:
    - "tests/"
    - "example/"

checks:
  php: true

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true

build:
  nodes:
    tests:
      environment:
        php:
          version: 7.4

  tests:
    override:
      - php-scrutinizer-run
      - command: 'php ./vendor/bin/phpunit --coverage-clover=coverage-clover'
        coverage:
          file: 'coverage-clover'
          format: 'php-clover'
